CFLAGS += `pkg-config --cflags --libs goptfoo jkiss`
CFLAGS += -lpthread

bias: bias.c

customseed: customseed.c

threadrate: threadrate.c

uniform-bias: uniform-bias.c

clean:
	@-rm -f bias customseed threadrate uniform-bias 2>/dev/null
